language: cpp

before_install:
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 50
  - sudo pip install cpp-coveralls

install: 
  - curl -L -o cpputest-3.7.2.tar.gz https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.7.2.tar.gz?raw=true
  - tar xvzf cpputest-3.7.2.tar.gz
  - mv cpputest-3.7.2 cpputest && cd cpputest
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - export CPPUTEST_HOME=$TRAVIS_BUILD_DIR/cpputest

script: make

after_success:
  - coveralls --exclude cpputest --exclude unit_tester/tests --gcov-options '\-lp'

os: linux
